Repository woorifisa-service-dev-3rd/frontend-1st-pokemon-resume, pull requests merged in 2024-07, with the labels that each got.

#7 feat: main-html 추가
  main.html
  src/img/html_main.jpg
  src/img/metamong.png
  src/img/monster_ball.png
  src/img/monsterball.png
  src/img/sun.png
Labels: feature

#3 Feature: html-modal-page
  modal.html
Labels: feature

#13 docs: api request/response 문서 생성
  docs/api.md
Labels: documentation

#18 feat: bgm을 추가하였습니다.
  index.html
  main.html
  reset.css
  src/audio/poke__bgm.mp3
Labels: feature

#19 feat: 하이퍼링크 작성
  modal.html
Labels: feature

#20 Feature/#14
  main.html
Labels: feature

#21 feat : 스타일 작성
  style.css
Labels: feature

#23 design: bgm 버튼 디자인을 넣었습니다.
  main.html
Labels: feature

#25 docs: 포맷팅
  modal.html
Labels: documentation

#26 docs : 포맷팅
  modal.html
Labels: documentation

#27 feat : text 클래스 가져옴
  modal.html
  style.css
Labels: feature

#30 feat: 텍스트를 한글자씩 보여주는 기능 추가
  main.html
Labels: feature

#31 Feature/#11
  modal.html
  package.json
  stats.html
  stats.js
  style.css
Labels: feature

#32 Feature/#28
  main.html
  modal.html
  style.css
Labels: feature

#38 Feature : 정렬 및 스타일 수정
  modal.html
  reset.css
  style.css
Labels: documentation

#41 fix: 글자가 합쳐지는 버그와 몬스터볼 선택후 다른 몬스터볼 선택시 데이터가 바뀌는 버그를 수정하였습니다.
  app.js
  index.html
  modal.html
  src/audio/poke__bgm.mp3
Labels: bug

#53 Feature/#52
  lib/types/type.tsx
  lib/utils/Firebase.ts
  lib/utils/auth.ts
  lib/utils/db.ts
  lib/utils/firebaseApp.ts
Labels: feature
